puts "Kalu".object_id
puts "Kalu".object_id
puts "Kalu".object_id
puts "Kalu".object_id
puts "Kalu".object_id
puts "==============="
puts :kalu.object_id
puts :kalu.object_id
puts :kalu.object_id
puts :kalu.object_id
puts :kalu.object_id
puts :kalu.object_id
